### ISSUE TITLE
Make default commit message configurable

### ISSUE THREAD

**Issue by rustyx** [trevorr/vss2git#20]
Currently the default commit message (for when the VSS check-in message is blank) seems to be hard-coded to "Vss2Git".

I prefer to not have "Vss2Git" but something else e.g. "-".

Thus requesting to make the default message configurable.

It is also possible to commit with an empty message in GIT.
The parameter for that is `--allow-empty-message`.
Then a default message won't even be needed.

**Comment by trevorr** [comment]
The commit message now defaults to blank. It's not configurable from the UI, but blank seems to be what most people want.

**Comment by sgaulding** [comment]
@trevorr: If you want it I have a branch will allow setting defaults with UI.

Branch: [SetDefaultCommentByUI](https://github.com/sgaulding/vss2git/tree/feature/SetDefaultCommentByUI)
Commit: 02bdb7a6f8593c818d84e04336ab302764b4709b
