### ISSUE TITLE
ERROR: Failed to read revisions for $/OT'S/2016/PM1908_Reportes_Stros (PATFAAAA): Attempted read of 1869832048 bytes with only 1188150 bytes remaining in buffer Hpdi.VssPhysicalLib.RecordTruncatedException: Attempted read of 1869832048 bytes with only 1188150 bytes remaining in buffer

### ISSUE THREAD

**Issue by caom838** [trevorr/vss2git#47]
Hi, I have this error

ERROR: Failed to read revisions for $/OT'S/2016/PM1908_Reportes_Stros (PATFAAAA): Attempted read of 1869832048 bytes with only 1188150 bytes remaining in buffer
Hpdi.VssPhysicalLib.RecordTruncatedException: Attempted read of 1869832048 bytes with only 1188150 bytes remaining in buffer
   en Hpdi.VssPhysicalLib.VssRecordFile.ReadRecord(VssRecord record) en C:\Users\covalle\Downloads\vss2git-master\VssPhysicalLib\VssRecordFile.cs:línea 62
   en Hpdi.VssPhysicalLib.NameFile.GetName(Int32 offset) en C:\Users\covalle\Downloads\vss2git-master\VssPhysicalLib\NameFile.cs:línea 44
   en Hpdi.VssLogicalLib.VssDatabase.GetFullName(VssName name) en C:\Users\covalle\Downloads\vss2git-master\VssLogicalLib\VssDatabase.cs:línea 184
   en Hpdi.VssLogicalLib.VssDatabase.GetItemName(VssName name, String physicalName) en C:\Users\covalle\Downloads\vss2git-master\VssLogicalLib\VssDatabase.cs:línea 196
   en Hpdi.VssLogicalLib.VssRevision.CreateAction(RevisionRecord revision, VssItem item) en C:\Users\covalle\Downloads\vss2git-master\VssLogicalLib\VssRevision.cs:línea 137
   en Hpdi.VssLogicalLib.VssProject.CreateRevision(RevisionRecord revision, CommentRecord comment) en C:\Users\covalle\Downloads\vss2git-master\VssLogicalLib\VssProject.cs:línea 99
   en Hpdi.VssLogicalLib.VssItem.VssRevisionEnumerator`2.get_Current() en C:\Users\covalle\Downloads\vss2git-master\VssLogicalLib\VssItem.cs:línea 227
   en Hpdi.Vss2Git.RevisionAnalyzer.ProcessItem(VssItem item, String path, PathMatcher exclusionMatcher) en C:\Users\covalle\Downloads\vss2git-master\Vss2Git\RevisionAnalyzer.cs:línea 188

Do you know why or what can I do? 
Thanks

**Comment by trevorr** [comment]
I just merged a fix from @kornman00 submitted by @ifcaro. Please try again with the latest from `master`. I'm closing the issue for now, but if the problem persists, feel free to reopen it.
