### ISSUE TITLE
Can this be used to read the VSS files on the client machine?

### ISSUE THREAD

**Issue by rfalanga** [trevorr/vss2git#54]
I've got an old Visual Studio projects with code for a WPF app, that we used to have saved in Visual SourceSafe. I'd like to now move that code into Git. This project was pointed out to me as a possible solution. However, looking at vss2git, it appears to me that it only works against the VSS data store on the server where VSS was kept. That server is long since gone and the VSS database never backed up. Can I use vss2git to save what I have into Git? Or do I ignore the VSS specific files and just save all of the files in the Visual Studio projects instead?

**Comment by trevorr** [comment]
vss2git works against the VSS repository files. It doesn't need a "VSS server" (which is really just a file share and shouldn't be accessed directly by vss2git anyway). If you only have files that were checked out from VSS (e.g. the latest versions), you don't need vss2git at all.

**Comment by rfalanga** [comment]
Perfect, thank you.
